import 'package:flutter/material.dart';
import '../colors.dart';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Terms of Service'),
        backgroundColor: Colors.transparent,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Terms of Service',
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'Last updated: March 15, 2025',
              style: TextStyle(
                fontSize: 14,
                color: Colors.grey[400],
              ),
            ),
            const SizedBox(height: 24),
            const Text(
              'Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Grivora mobile application (the "Service") operated by Grivora Team ("us", "we", or "our").',
              style: TextStyle(
                fontSize: 16,
                color: Colors.white,
              ),
            ),
            const SizedBox(height: 16),
            _buildSectionTitle('1. Your Use of the Service'),
            _buildSectionContent(
                'By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service.\n\nYou must be at least 13 years old to use the Service. By using the Service, you represent and warrant that you meet all eligibility requirements.'),
            _buildSectionTitle('2. Content'),
            _buildSectionContent(
                'Our Service allows you to engage with AI characters, share and obtain information. You are responsible for the data you share with the Service.\n\nBy using the Service, you grant us a non-exclusive, transferable, sub-licensable, royalty-free, worldwide license to use, modify, and analyze any content that you submit through the Service.'),
            _buildSectionTitle('3. Intellectual Property'),
            _buildSectionContent(
                'The Service and its original content, features, and functionality are and will remain the exclusive property of Grivora Team and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of Grivora Team.'),
            _buildSectionTitle('4. Termination'),
            _buildSectionContent(
                'We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.\n\nAll provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.'),
            _buildSectionTitle('5. Disclaimer'),
            _buildSectionContent(
                'Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied.\n\nAI characters are simulations and do not represent real individuals or entities. Responses generated by AI characters are based on patterns in training data and may not always be accurate, complete, or appropriate.'),
            _buildSectionTitle('6. Limitation of Liability'),
            _buildSectionContent(
                'In no event shall Grivora Team, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.'),
            _buildSectionTitle('7. Changes'),
            _buildSectionContent(
                'We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms.'),
            _buildSectionTitle('8. Contact Us'),
            _buildSectionContent(
                'If you have any questions about these Terms, please contact us at support@grivora.com.'),
            const SizedBox(height: 24),
            Center(
              child: Text(
                '© 2025 Grivora. All rights reserved.',
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.grey[400],
                ),
              ),
            ),
            const SizedBox(height: 40),
          ],
        ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.bold,
        ),
      ),
    );
  }

  Widget _buildSectionContent(String content) {
    return Text(
      content,
      style: const TextStyle(fontSize: 16),
    );
  }
}
